### ISSUE TITLE
No shell?

### ISSUE THREAD

**Issue by xGLogic** [qbcore-framework/qb-ifruitstore#4]
Everything works fine, except the part when i tried finding the ifruitstore, there is no shell at all? You can thermite the panels as the coords show and it defuses the alarm, but when you go and look for the store there is nothing there, it leads me to the unshelled store in the photo below, as there is also no coords for the main location in the config, is this still a work in progress or am i just missing the shell? . Any idea?
![20210903062408_1](https://user-images.githubusercontent.com/90045260/132012766-9544b810-adec-4587-baf4-8addd9248c77.jpg)

**Comment by Synthethics** [comment]
You need an MLO, the default release does not include one.

**Comment by DishDawgGaming** [comment]
> You need an MLO, the default release does not include one.

Do you know where to get the mlo for this location? Cause the only MLO I see for it is on vinewood blvd, not near this store location.
